apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  #labels: {app:myapp, tier:frontend, roll:client}
  labels:
    app: myapp
    tier: frontend
    roll: client
spec:
  containers:
  - name: pod-demo-c1
    image: ikubernetes/myapp:v1
  - name: pod-demo-c2
    image: busybox
    #command: ["/bin/sh", "-c", "sleep 3600"]
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 3600"
