apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
  #labels: {app:myapp, tier:frontend, roll:client}
  labels:
    app: myapp
    tier: frontend
    roll: client
  annotations:
    notyun.com/created-by: ZDNS-Ycy
spec:
  nodeSelector:
    disksize: large
  containers:
  - name: pod-demo-c1
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    - name: https
      containerPort: 443
  - name: pod-demo-c2
    image: busybox
    imagePullPolicy: IfNotPresent
    #command: ["/bin/sh", "-c", "sleep 3600"]
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 3600"
