apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
  namespace: default
  labels:
    app: myapp
    roll: test
spec:
  containers:
  - name: liveness-exec-pod-c1
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    - "touch /tmp/healthy;sleep 60;rm -fr /tmp/healthy;sleep 3600"
    livenessProbe:
      exec:
        command: ["test", "-e", "/tmp/healthy"]
      initialDelaySeconds: 3
      periodSeconds: 2
  restartPolicy: Always
