apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      release: canary
      app: myapp
  template:
    metadata:
      name: rs-demo-temp
      labels:
        release: canary
        app: myapp
        roll: db
    spec:
      containers:
      - name: rs-demo-temp-c1
        image: ikubernetes/myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
