apiVersion: v1
kind: Pod
metadata:
  name: pod-nfs
  namespace: default
  labels:
    app: myapp
    tier: frontend
    roll: client
spec:
  containers:
  - name: pod-nfs-c1
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: vol-1
      mountPath: /usr/share/nginx/html
  - name: pod-nfs-c2
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true;do echo $(date) >> /data/index.html;sleep 2;done"]
    volumeMounts:
    - name: vol-1
      mountPath: /data/
  volumes:
  - name: vol-1
    nfs:
      server: 202.173.9.42
      path: /k8s/data/volumes
      readOnly: false
