apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-env
  namespace: default
  #labels: {app:myapp, tier:frontend, roll:client}
  labels:
    app: myapp
    tier: frontend
    roll: client
spec:
  containers:
  - name: secret-pod-env-c1
    image: ikubernetes/myapp:v1
    env:
    - name: MYSQL_PWD
      valueFrom:
        secretKeyRef:
          name: secret-mysql-pwd 
          key: password
          optional: true
