apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-a
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      quality: fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-b
  namespace: default
spec:
  #accessModes: ["ReadWriteOnce"]
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 500Mi
---
