apiVersion: v1
kind: Pod
metadata:
  name: pod-rbd
spec:
  containers:
    - image: busybox
      name: pod-rbd
      command: ["sleep", "60000"]
      volumeMounts:
      - name: rbdpd
        mountPath: /mnt/rbd
        readOnly: false
  volumes:
    - name: rbdpd
      rbd:
        monitors: 
        - '172.16.2.32:6789'
        pool: rbd
        image: foo
        fsType: ext4
        readOnly: true
        user: admin
        secretRef:
          name: ceph-secret
