apiVersion: v1
kind: Service
metadata:
  name: stateful-svc-myapp
  namespace: default
spec:
  clusterIP: None
  selector:
    app: myapp-pod
  ports:
  - port: 80
    name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-myapp
spec:
  serviceName: stateful-svc-myapp
  replicas: 3
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      name: statefulset-myapp-temp
      labels:
        app: myapp-pod
    spec:
      containers:
      - name: statefulset-myapp-temp-c1
        image: ikubernetes/myapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: myappdata
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: myappdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
