apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader
rules:
#- apiGroups:
#  - ""
#  - "deployments"
#  - "apps"
#  resources:
#  - 'deployments'
#  verbs:
#  - get
#  - list
#  - watch
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
