apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yuchunyun-pods-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pods-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: yuchunyun
