apiVersion: v1
kind: Pod
metadata:
  name: sa-pod
  namespace: default
  #labels: {app:myapp, tier:frontend, roll:client}
  labels:
    app: myapp
    tier: frontend
    roll: client
spec:
  containers:
  - name: sa-pod-c1
    image: ikubernetes/myapp:v1
  serviceAccountName: sa-test
