apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-http
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-tcp-53
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - name: tcp
    port: 53
    targetPort: 53
    protocol: TCP
    nodePort: 30053
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-udp-53
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - name: udp
    port: 53
    targetPort: 53
    protocol: UDP
    nodePort: 30054
