apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - name: ceph-rbd
      mountPath: /tmp
      readOnly: true
  volumes:
  - name: ceph-rbd
    configMap:
      name: ceph-rbd
