apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-2
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
  clusterIP: 10.98.98.98
  type: NodePort
  ports:
  - name: myapp
    nodePort: 30000
    port: 8090
    targetPort: 80
