apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: default
spec:
  selector:
    app: myapp
    release: canary
  clusterIP: 10.97.97.97
  type: ClusterIP
  ports:
  - name: http
    #nodePort:
    port: 8080
    targetPort: 80
