kind: ConfigMap
apiVersion: v1
metadata:
  name: mydns-tcp-vs
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 53,
          "serviceName": "mydns-tcp",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "tcp",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 53,
            "bindAddr": "172.16.8.10"
          },
          "partition": "kubernetes",
          "balance": "least-connections-member",
          "mode": "tcp"
        }
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mydns-udp-vs
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 53,
          "serviceName": "mydns-udp",
          "healthMonitors": [{
            "interval": 30,
            "protocol": "udp",
            "timeout": 120
          }]
        },
        "frontend": {
          "virtualAddress": {
            "port": 53,
            "bindAddr": "172.16.8.10"
          },
          "partition": "kubernetes",
          "balance": "least-connections-member",
          "mode": "udp"
        }
      }
    }
